import { useEffect, useState } from "react";
import { FileDown } from "lucide-react";

import { ApiError, getReports } from "../api/client";
import {
  EmptyPanel,
  ErrorPanel,
  LoadingPanel,
  reportDisplayName,
} from "../components/Ui";
import type { ReportLink } from "../types/api";

export function ReportsPage() {
  const [reports, setReports] = useState<ReportLink[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    void getReports()
      .then((response) => setReports(response.reports))
      .catch((caughtError) =>
        setError(
          caughtError instanceof ApiError
            ? caughtError.message
            : "Unable to load reports.",
        ),
      )
      .finally(() => setLoading(false));
  }, []);

  return (
    <section className="page-section">
      <div className="page-heading">
        <div>
          <span className="eyebrow">Reports</span>
          <h2>Security report center</h2>
          <p>
            Review authenticated, same-origin security artifacts generated by
            scans, comparisons, inventory, and intelligence workflows.
          </p>
        </div>
      </div>

      {loading ? <LoadingPanel message="Loading security reports…" /> : null}
      {error ? <ErrorPanel message={error} /> : null}

      {!loading && !error && !reports.length ? (
        <EmptyPanel
          title="No reports available"
          detail="Generate a scan or analysis artifact to populate the report center."
        />
      ) : null}

      {!loading && !error && reports.length ? (
        <div className="report-grid">
          {reports.map((report) => (
            <a
              className="report-card"
              key={`${report.run_id}-${report.filename}`}
              href={report.download_url}
            >
              <div className="report-card-icon" aria-hidden="true">
                <FileDown size={19} />
              </div>
              <div>
                <strong>{reportDisplayName(report.filename)}</strong>
                <span title={report.filename}>{report.filename}</span>
                <small>{report.run_id}</small>
              </div>
            </a>
          ))}
        </div>
      ) : null}
    </section>
  );
}
